server:
  port: 8040
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        server-addr: 101.200.130.236:8848
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他的微服务
          enabled: true
      routes:
        - id: path_route1
          uri: lb://user-center
          predicates:
            - Path=/users/**
        - id: path_route2
          uri: lb://content-center
          predicates:
            - Path=/shares/**
        - id: path_route3
          uri: lb://content-center
          predicates:
            - Path=/notice/**

      #- id: path_route #路由的ID
      ##          uri: http://localhost:8010/users/{id} #匹配后路由地址
      ###          uri: lb://user-center
      ##          predicates: # 断言，路径相匹配的进行路由
      ##            - Path=/users/{id}
      ###            - Before=2020-10-10T16:50:42.579+08:00[Asia/Shanghai]
      ###            - Method=GET
      ##            - TimeBetween=下午1:00,下午5:00

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: trace

